services:
  web:
    image: php:8.3-apache
    container_name: php_apache
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    restart: unless-stopped
